<#-- 
	描述：颜色选择框
	作者：黄磊 
	版本：v1.0 
-->
<#macro colorPicker id>
<input name="ColorPicker1:ColorPicker1" type="text" id="ColorPicker1_ColorPicker1" class="FormBase" onfocus="this.className='FormFocus';" onblur="this.className='FormBase';" size="8" /><img src="../images/colorpicker.gif" id="ColorPicker1_ColorPreview" onclick="IsShowColorPanel('ColorPicker1_ColorPicker1','ColorPreview',0,0)" class="img" title="选择颜色" /><span id="ColorPickerColorPicker1_ColorPicker1" style="display:none; position:absolute;z-index:500;" onmouseout="HideColorPanel('ColorPicker1_ColorPicker1');"  onmouseover="ShowColorPanel('ColorPicker1_ColorPicker1','ColorPicker1_ColorPreview',0,0);"><div  style="display:block;cursor:crosshair;z-index:501" class="article" ><table border=0 cellPadding=0 cellSpacing=10 onmouseover="ShowColorPanel('ColorPicker1_ColorPicker1','ColorPicker1_ColorPreview',0,0);"><tbody><tr><script language="javaScript">WriteColorPanel('ColorPicker1_ColorPicker1','ColorPicker1_ColorPreview',0,0);</script></tr></tbody></table><table style="font-size:12px;word-break:break-all;width:100%;border:0px"  cellPadding=0 cellSpacing=10 onmouseover="ShowColorPanel('ColorPicker1_ColorPicker1','ColorPicker1_ColorPreview',0,0);"><tbody><tr><td align=middle rowSpan=2>选中色彩<table border=1 cellPadding=0 cellSpacing=0 height=30 id=ShowColorColorPicker1_ColorPicker1 width=40 bgcolor=""><tbody><tr><td></td></tr></tbody></table></td><td rowSpan=2>基色: <SPAN id=RGBColorPicker1_ColorPicker1></SPAN><br />亮度: <SPAN id=GRAYColorPicker1_ColorPicker1>120</SPAN><br />代码: <INPUT id=SelColorColorPicker1_ColorPicker1 size=7 value="" border=0></TD><td><input type="button" onclick="javascript:ColorPickerOK('ColorPicker1_ColorPicker1','ColorPicker1_ColorPreview');" value="确定"></TD></TR><tr><td><input type="button" onclick="javascript:document.getElementById('ColorPicker1_ColorPicker1').value='';document.getElementById('ColorPicker1_ColorPreview').style.background='#FFFFFF';HideColorPanel('ColorPicker1_ColorPicker1');" value="取消"></TD></tr></tbody></table></DIV><iframe id="pickcoloriframeColorPicker1_ColorPicker1" style="position:absolute;z-index:102;top:-1px;width:250px;scrolling:no;height:237px;" frameborder="0"></iframe></span><script language=javascript>
InitColorPicker('ColorPicker1_ColorPreview','');
</script>
</#macro>